# Replit Deployment Configuration for Emergency First Aid App

[build]
# Standard npm build command for deployment
run = "npm run build"

[start]
# Standard production server startup command
run = "npm start"

[env]
# Environment variables for production
NODE_ENV = "production"
PORT = "5000"
SESSION_SECRET = "emergency-first-aid-app-secret-key-2024"

[deployment]
# Deployment-specific settings
build = true
deploymentTarget = "gce"